:api_key: c3510f6e258e9aaebcb437e93bc1dfec
:password: 68eff0e522e0cf55e51b2beb385abdc0
:theme_id: "65"
:preview_url: https://demo-ideasports.commercesuite.com.br/loja/loja.php?loja=1299870&opencode_theme=670c40ab-911c-4ccb-a7a1-631d0a0a3254
:debug: false
